### ISSUE TITLE
More detailed explanation

### ISSUE THREAD

**Issue by BinWang28** [dawenzi123/DAGCN#1]
Can more explanation be provided? Many thanks.

**Comment by dawenzi123** [comment]
Sorry for the inconvenience, a cleaner version will come in the next couple days with clear instructions.

For now, you can run the program as follow.

1. under the "s2v/" directory, run command "make -j4" to compile the necessary c++ files.

2. after that, run "./run_DGCNN.sh" would start the program with the default config.

Other configs could be done by using

./run_DGCNN.sh DATANAME FOLD

this would let the program run on dataset = DATANAME with fold number = FOLD ( 1-10 corresponds to which fold to use as test data in cross-validation experiments. 0 for 10-fold cross-validation)

**Comment by Kevin-chen-sheng** [comment]
![image](https://user-images.githubusercontent.com/52196486/66907388-d6dc2880-f03b-11e9-9412-c28d55badb44.png)
Is there a missing parameter here?
