### ISSUE TITLE
.mat data

### ISSUE THREAD

**Issue by tiredDi** [dawenzi123/DAGCN#3]
Thanks for your sharing
I opened the .mat file and can't understand this data's inforamtion, Could you tell me what it meas and how can I generate a xx.mat file
Looking forward to your reply

**Comment by Kevin-chen-sheng** [comment]
Hello,
have you solved this problem?

**Comment by dawenzi123** [comment]
Sorry for the late reply

Check the "data/README.md" for the format.

There are two preprocessing scripts in MATLAB: "mat2txt.m" transforms .mat graphs (from Weisfeiler-Lehman Graph Kernel Toolbox), "dortmund2txt.m" transforms graph benchmark datasets downloaded from https://ls11-www.cs.tu-dortmund.de/staff/morris/graphkerneldatasets

**Comment by Kevin-chen-sheng** [comment]
From the above url, I can't find the two scripts you mentioned
