### ISSUE TITLE
build my own  training data

### ISSUE THREAD

**Issue by Kevin-chen-sheng** [dawenzi123/DAGCN#5]
Thanks for your sharing

how to build my own  training data according to your format. Generate a .mat file first?
Looking forward to your reply，Sincerely.

**Comment by hanmenghan** [comment]
If you already have data, just store it in. Mat file format.
Maybe you need this:
```
import scipy.io as sio
sio.savemat()
```

**Comment by dawenzi123** [comment]
Sorry for the late reply

Check the "data/README.md" for the format.

There are two preprocessing scripts in MATLAB: "mat2txt.m" transforms .mat graphs (from Weisfeiler-Lehman Graph Kernel Toolbox), "dortmund2txt.m" transforms graph benchmark datasets downloaded from https://ls11-www.cs.tu-dortmund.de/staff/morris/graphkerneldatasets


Personally, you can also create your own datasets based on the format of loading method in util.py
